package com.example.tfm.util

import android.content.Context
import android.graphics.drawable.Drawable
import com.example.tfm.model.Emoji

class EmojiUtil(context: Context) {


    private val emojiFaceList = arrayListOf(
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/1.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/2.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/3.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/4.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/5.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/6.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/7.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/8.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/9.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/10.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/12.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/13.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/14.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/15.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/16.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/17.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/20.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/21.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/23.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/24.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/25.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/27.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/28.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/29.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/30.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/31.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/32.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/33.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/34.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/35.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/36.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/37.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/38.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/39.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/40.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/41.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/42.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/43.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/44.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/45.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/46.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/47.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/48.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/49.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/50.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/51.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/52.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/53.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/54.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/55.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/56.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/57.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/58.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/59.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/60.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/61.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/62.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/63.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/64.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/65.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/66.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/67.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/68.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/69.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/70.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/71.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/72.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/73.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/74.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/75.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/76.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/77.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/78.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/79.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/80.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/81.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/82.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/83.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/84.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/85.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/86.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/87.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/88.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/89.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/90.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/91.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/92.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/93.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/100.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/101.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/104.png"), null), getEmojiUnicode(0x1F4A2))
        )

    fun getEmojiFace() = emojiFaceList

    private fun getEmojiUnicode(unicode: Int): String{
        return String(Character.toChars(unicode))
    }
}