package com.example.tfm.util

import android.content.Context
import android.graphics.drawable.Drawable
import com.example.tfm.model.Emoji

class EmojiUtil(context: Context) {


    private val emojiFaceList = arrayListOf(
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/1.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/2.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/3.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/4.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/5.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/6.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/7.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/8.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/9.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/10.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/12.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/13.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/14.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/15.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/16.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/17.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/20.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/21.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/23.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/24.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/25.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/27.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/28.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/29.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/30.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/31.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/32.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/33.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/34.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/35.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/36.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/37.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/38.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/39.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/40.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/41.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/42.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/43.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/44.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/45.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/46.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/47.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/48.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/49.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/50.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/51.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/52.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/53.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/54.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/55.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/56.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/57.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/58.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/59.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/60.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/61.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/62.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/63.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/64.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/65.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/66.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/67.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/68.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/69.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/70.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/71.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/72.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/73.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/74.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/75.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/76.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/77.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/78.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/79.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/80.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/81.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/82.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/83.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/84.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/85.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/86.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/87.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/88.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/89.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/90.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/91.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/92.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/93.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/100.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/101.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/104.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/adult.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/alien.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/alienmonster.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/angersymbol.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/babyangel.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/babyemoji.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald1.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald2.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald4.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/basketball.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bathemoji.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/beard.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/blond.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body1.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body2.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body3.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body4.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body5.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body6.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body7.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body8.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body10.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body11.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body12.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body13.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body15.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body16.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body17.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body18.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body19.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body20.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body21.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body22.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body24.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body25.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body27.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body28.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body29.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body30.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body31.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body32.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body33.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body34.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body35.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body38.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body39.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body40.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body41.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bomb.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bone.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/boy.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/brain.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/breast.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bride.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bust.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/busts.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat1.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat2.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat3.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat4.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat5.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat6.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat7.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat8.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat9.png"), null), getEmojiUnicode(0x1F4A2)),
        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/child.png"), null), getEmojiUnicode(0x1F4A2))
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/constructor.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple19.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dancer.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dash.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/detective.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dizzt.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/ear.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/elf.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/explosion.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/eye.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/eye1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/eye2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/facemassage.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/faceok.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/facepalm.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/facepalm2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/fairy.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/family1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/family2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/family3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/family4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/family5.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalegradua.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalejudge.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalemech.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femaleoffice.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalepilot.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalepolice.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalescien.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalesing.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femalesleuth.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femaleteacher.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femaletech.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/femaleworker.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/fencer.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/footprint.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/genie.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/ghost.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/girl.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/golfer.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/guardman.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/handwritting.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/happraising.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/haricut.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heart1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartarrow.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartbeating.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartblack.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartblue.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartbroken.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartdeco.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartexclamation.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartgif.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartgreen.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartheavy.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartgrowing.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartorange.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartpurple.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartrevolving.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/heartsparkling.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/hearttwo.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/hole.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/horseracer.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/hundred.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/information.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/japa1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/japa2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job5.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job6.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job7.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job8.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/job20.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/juggler.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/kiss.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/kiss1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/kiss2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/kiss3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/kiss4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/80.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/81.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/82.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/83.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/84.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/85.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/86.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/87.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/88.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/89.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/90.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/91.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/92.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/93.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/100.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/101.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/104.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/adult.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/alien.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/alienmonster.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/angersymbol.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/babyangel.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/babyemoji.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bald4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/basketball.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bathemoji.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/beard.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/blond.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body5.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body6.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body7.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body8.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body10.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body11.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body12.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body13.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body15.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body16.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body17.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body18.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body19.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body20.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body21.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body22.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body24.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body25.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body27.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body28.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body29.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body30.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body31.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body32.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body33.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body34.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body35.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body38.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body39.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body40.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/body41.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bomb.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bone.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/boy.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/brain.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/breast.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bride.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/bust.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/busts.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat3.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat5.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat6.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat7.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat8.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/cat9.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/child.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/constructor.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/coup4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple1.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple2.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple4.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/couple19.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dancer.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dash.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/detective.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/dizzt.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/ear.png"), null), getEmojiUnicode(0x1F4A2)),
//        Emoji(Drawable.createFromStream(context.assets?.open("emojifaces/elf.png"), null), getEmojiUnicode(0x1F4A2))
        )

    fun getEmojiFace() = emojiFaceList

    private fun getEmojiUnicode(unicode: Int): String{
        return String(Character.toChars(unicode))
    }
}